repos:
-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black
        args: [--safe, --quiet]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: check-yaml
    -   id: debug-statements
        exclude: _pytest/(debugging|hookspec).py
        language_version: python3
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.6.1
    hooks:
    -   id: autoflake
        name: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]
        language: python
        files: \.py$
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-no-pep420
          - flake8-tidy-imports
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.3
    hooks:
    -   id: reorder-python-imports
        args: ['--application-directories=.:src', --py37-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
