name: Test

on: [pull_request]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  pip install --upgrade pip
                  pip install poetry
                  poetry export -f requirements.txt --output requirements.txt
                  pip install -r requirements.txt
                  pip install pytest
                  pip install pytest-cov
            - name: Generate coverage report
              run: pytest --cov=./ --cov-report=xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: ./coverage/reports/
                  fail_ci_if_error: true
                  files: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
                  path_to_write_report: ./coverage/codecov_report.txt
                  verbose: true
